### ISSUE TITLE
High battery usage thanks to `convert`?

### ISSUE THREAD

**Issue by TheGag96** [dylanaraps/wal#35]
I set up wal more or less as described in the repo's README, and I noticed my laptop's battery was being heavily drained since. I checked powertop, and it seemed that `convert` from ImageMagick appears to be running constantly and taking up a lot of CPU time (~1000 ms/s). Is wal setting the desktop wallpaper every frame or something? Is there a way to mitigate any of this? Thanks.

**Comment by dylanaraps** [comment]
I'll look into this, thanks for reporting it.

**Comment by dylanaraps** [comment]
Try out the latest master and let me know if the issue still occurs.

**Comment by TheGag96** [comment]
I think this actually fixed it! `convert` does not show up in powertop anymore. Thanks for fixing this so quickly! If something comes up again I'll make another issue.

**Comment by dylanaraps** [comment]
No problem, thanks for reporting it. I think this was also the cause of my
laptop's battery drain so I'm glad it's fixed now too. :)

**Comment by TheGag96** [comment]
Scratch that, it is not fixed, unforunately... [Here](http://i.imgur.com/Q3FTPFz.png) is a screenshot of what Powertop outputs. Strangely, it seems to come and go... I know when it's causing problems because my fan will spin incessantly for a while lol. Why would it be running for more than a fraction of a second...?

**Comment by dylanaraps** [comment]
`convert` is only called when a colorscheme needs to be generated for the first time. Once the scheme is generated `wal` will just use the cache file directly.

When `convert` generates a scheme we actually call it multiple times. Basically we loop and each loop we ask `convert` to make a larger palette. We stop looping when `convert` successfully generates `16` colors.

The issue is probably the loop going on forever. The solutions are to either:

- Add a timeout to the loop.
    - Stop it from calling `convert` endlessly.
- Kill all child processes when we kill `wal`.

I'll start working on these. :+1:

**Comment by dylanaraps** [comment]
Try out the latest master, I've added a timeout to the loop and also made it so all child processes are killed too.

**Comment by TheGag96** [comment]
After a week of testing, it appears to work just fine for me! No rogue `convert` processes anywhere. Thanks a ton!
